# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cleed < Formula
  desc "A simple feed reader for the command line"
  homepage "https://github.com/radulucut/cleed"
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/radulucut/cleed/releases/download/v0.1.2/cleed_Darwin_x86_64.tar.gz"
      sha256 "c4779b68c5d3ec2c0f96a9a55fb187f999f6cca7b2787ebdbaf6d83c5b849f48"

      def install
        bin.install "cleed"
      end
    end
    on_arm do
      url "https://github.com/radulucut/cleed/releases/download/v0.1.2/cleed_Darwin_arm64.tar.gz"
      sha256 "3d5f2ea6528acdd0cdd23e811cc47f3f464d828b9910f9bd8a560a17c299e81a"

      def install
        bin.install "cleed"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/radulucut/cleed/releases/download/v0.1.2/cleed_Linux_x86_64.tar.gz"
        sha256 "4babf499e7e277b1803af917d168180f6506f8de7d2a13b7376282a9a529e3d7"

        def install
          bin.install "cleed"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/radulucut/cleed/releases/download/v0.1.2/cleed_Linux_arm64.tar.gz"
        sha256 "9ffac785542daca5bfd5b71a638c9f9e079c7723264c6c85a8d4ae50ca12a51b"

        def install
          bin.install "cleed"
        end
      end
    end
  end
end
